# Generated by Django 4.2.3 on 2023-08-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pokemon_pokemon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png'),
        ),
    ]
